---
server:
  listen_ip: 0.0.0.0
  listen_port: 443
  timeout: 30s
  idle_timeout: 30s
  tls_context:
    certificate_path: localhost.pem
    private_key_path: localhost-key.pem

upstreams:
  - name: httpbin
    connect_timeout: 5s
    url: https://httpbin.org

routes:
  - host: localhost
    http:
      paths:
        - path: /
          upstream: httpbin
        - path: /json
            upstream: httpbin
            auth_enabled: false

identity:
  provider: auth0
  client_id: long-hash-here
  client_secret: long-hash-here
  oauth2:
    domain: https://yourtenant.auth0.com
    callback: https://localhost/callback
    auth_url: https://yourtenant.auth0.com/authorize
    token_url: https://yourtenant.auth0.com/oauth/token

jwt:
  shared_secret: replace-this-with-a-long-hash
  expires: 10h
