---
server:
  listen_ip: 0.0.0.0
  listen_port: 443
  timeout: 30s
  idle_timeout: 30s
  tls_context:
    certificate_path: localhost.pem
    private_key_path: localhost-key.pem

upstreams:
  - name: httpbin
    connect_timeout: 5s
    url: https://httpbin.org

routes:
  - host: localhost
    rules:
      - request.host == 'localhost'
    http:
      paths:
        - path: /
          upstream: httpbin

  - host: 127.0.0.1
    http:
      paths:
        - path: /
          upstream: httpbin
          auth_enabled: false

identity:
  provider: auth0
  client_id: long-hash-here
  client_secret: long-hash-here
  oauth2:
    auth_url: https://yourtenant.auth0.com/authorize
    token_url: https://yourtenant.auth0.com/oauth/token
    profile_url: https://yourtenant.auth0.com/userinfo
    state_secret: long-hash-here

jwt:
  secret: replace-this-with-a-long-hash
  expires: 10h
