---
server:
  listen_ip: 0.0.0.0
  listen_port: 443
  timeout: 30s
  idle_timeout: 30s
  tls_context:
    certificate_path: localhost.pem
    private_key_path: localhost-key.pem

upstreams:
  - name: httpbin
    connect_timeout: 5s
    url: https://httpbin.org

routes:
  - host: localhost
    http:
      paths:
        - path: /
          upstream: httpbin
